######################################################################
# Automatically generated by qmake (3.0) Di. Feb. 16 17:05:14 2016
######################################################################

CONFIG+=c++14
TEMPLATE = app
TARGET = tutorial
INCLUDEPATH += ../src

# Input
SOURCES += tutorial.cpp
