######################################################################
# Automatically generated by qmake (3.0) Di. Feb. 16 17:05:14 2016
######################################################################

TEMPLATE = app
TARGET = tutorial
QT -= gui
include(../src/verdigris.pri)

# Input
SOURCES += tutorial.cpp
