language: cpp

matrix:
  include:
    - name: osx clang qt5 -std=c++14
      os: osx
      compiler: clang
      env:
        - QMAKESPEC=macx-clang
      install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install qt5
      before_script:
        - brew link qt5 --force
        - which qmake
        - qmake --version

    - name: g++6 qt5.5.1 -std=c++14
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: ppa:beineri/opt-qt551-trusty
          packages:
            - g++-6
            - qt55base
      env:
        - STD_CPP=C++14
        - QT_VERSION=55
        - GCC_VERSION=6

    - name: g++6 qt5.6.3 -std=c++14
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: ppa:beineri/opt-qt563-trusty
          packages:
            - g++-6
            - qt56base
      env:
        - STD_CPP=C++14
        - QT_VERSION=56
        - GCC_VERSION=6

    - name: g++7 qt5.10.1 -std=c++14
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: ppa:beineri/opt-qt-5.10.1-xenial
          packages:
            - g++-7
            - qt510base
      env:
        - STD_CPP=C++14
        - QT_VERSION=510
        - GCC_VERSION=7

    - name: g++8 qt5.12.3 -std=c++17
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: ppa:beineri/opt-qt-5.12.3-xenial
          packages:
            - g++-8
            - qt512base
      env:
        - STD_CPP=C++17
        - QT_VERSION=512
        - GCC_VERSION=8

    - name: g++9 qt5.5.1 -std=c++14
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: ppa:beineri/opt-qt551-trusty
          packages:
            - g++-9
            - qt55base
      env:
        - STD_CPP=C++14
        - QT_VERSION=55
        - GCC_VERSION=9

    - name: clang-3.8 qt5.6.3 -std=c++14 -lib=stdc++-5
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
            - sourceline: ppa:beineri/opt-qt563-trusty
          packages:
            - clang-3.8
            - libstdc++-5-dev
            - qt56base
      env:
        - STD_CPP=C++14
        - QT_VERSION=56
        - CLANG_VERSION=3.8
        - QMAKESPEC=linux-clang

    - name: clang-3.9 qt5.7.1 -std=c++14 -lib=stdc++-5
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
            - sourceline: ppa:beineri/opt-qt571-trusty
          packages:
            - clang-3.9
            - libstdc++-5-dev
            - qt57base
      env:
        - STD_CPP=C++14
        - QT_VERSION=57
        - CLANG_VERSION=3.9
        - QMAKESPEC=linux-clang

    - name: clang-7 qt5.12.3 -std=c++17 -lib=libc++-7
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
            - sourceline: ppa:beineri/opt-qt-5.12.3-xenial
          packages:
            - clang-7
            - libc++abi-7-dev
            - libc++-7-dev
            - qt512base
      env:
        - STD_CPP=C++17
        - QT_VERSION=512
        - CLANG_VERSION=7
        - QMAKESPEC=linux-clang-libc++

    - name: clang-8 qt5.12.3 -std=c++17 -lib=libc++-7
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
            - sourceline: ppa:beineri/opt-qt-5.12.3-xenial
          packages:
            - clang-8
            - libc++abi-8-dev
            - libc++-8-dev
            - qt512base
      env:
        - STD_CPP=C++17
        - QT_VERSION=512
        - CLANG_VERSION=8
        - QMAKESPEC=linux-clang-libc++

    - name: qbs clang-8 qt5.12.3 -std=c++14
      os: linux
      services:
        - docker
      before_script: []
      script:
        - docker run -v${PWD}:/build
            arbmind/qbs-clang8-qt512:1
            build --file /build/verdigris.qbs --build-directory /tmp/build
            -p autotest-runner

before_script:
  - |
    if [[ $GCC_VERSION ]]; then
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${GCC_VERSION} 90
      g++ --version
    fi
  - |
    if [[ $CLANG_VERSION ]]; then
      ln -s $(which clang++-${CLANG_VERSION}) ~/bin/clang++
      clang++ --version
    fi
  - source /opt/qt$QT_VERSION/bin/qt${QT_VERSION}-env.sh
  - which qmake
  - qmake --version

script:
  - qmake -r "CONFIG+=${STD_CPP}"
  - make -j 2
  - make check
