name: Windows Tests

on: [push, pull_request]

jobs:
  windows-qbs:
    name: "${{ matrix.host_system }} Qbs Qt ${{ matrix.qt_version }} ${{ matrix.qt_arch }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - host_system: windows-2022
            vcvars: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat
            qt_version: "6.3.0"
            qt_arch: win64_msvc2019_64

          - host_system: windows-2019
            vcvars: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
            qt_version: "6.2.4"
            qt_arch: win64_msvc2019_64

    runs-on: "${{ matrix.host_system }}"
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: QtCache-${{ matrix.qt_version }}-${{ matrix.qt_arch }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "${{ matrix.qt_version }}"
          arch: "${{ matrix.qt_arch }}"
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Install Qbs
        run: choco install qbs

      - name: Setup Qbs
        run: |
          qbs setup-toolchains --type msvc $(cmd /c '"${{ matrix.vcvars }}" >nul & where cl') msvc
          qbs setup-qt $(cmd /c where qmake) qt
          qbs config profiles.qt.baseProfile msvc
          qbs config defaultProfile qt
          qbs config --list profiles

      - name: Git Checkout
        uses: actions/checkout@v2

      - run: >-
          qbs build
          --file verdigris.qbs
          --build-directory ${env:RUNNER_TEMP}\build
          -p autotest-runner

  windows-qmake:
    name: "${{ matrix.host_system }} QMake Qt ${{ matrix.qt_version }} ${{ matrix.qt_arch }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - host_system: windows-2022
            qt_version: "6.3.0"
            qt_arch: win64_msvc2019_64

          - host_system: windows-2019
            qt_version: "6.2.4"
            qt_arch: win64_msvc2019_64

    runs-on: "${{ matrix.host_system }}"
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: QtCache-${{ matrix.qt_version }}-${{ matrix.qt_arch }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "${{ matrix.qt_version }}"
          arch: "${{ matrix.qt_arch }}"
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Add msbuild to PATH
        uses: ilammy/msvc-dev-cmd@v1

      - name: Git Checkout
        uses: actions/checkout@v2

      - run: qmake -r
      - run: nmake
      - run: nmake check
